### ISSUE TITLE
Upload of Arducopter Firmware

### ISSUE THREAD

**Issue by Seeelefant** [spracing/ssbl#4]
If have some troble-or questions-uploading Arducopter to SP Racing H7 EXTREME. The description here https://github.com/spracing/ssbl talks about a file in bin format and of size 2 MB. Both does not hold for Arducopter-please help.

**Comment by hydra** [comment]
I'll try and get a documentation update done now that AP support for the SPRacingH7EXTREME is completed.

In the mean time there is documentation here on the AP website now: https://ardupilot.org/plane/docs/common-spracingh7-extreme.html#loading-firmware

**Comment by hydra** [comment]
I've updated the SSBL and documentation today, please see this:

https://github.com/spracing/ssbl#ardupilot-installation-to-external-flash

I also did a bit of testing and here's my results:

1) SP Racing BL + SSBL 1.0.1  + (any FC firmware) = Fail
2) SP Racing BL + SSBL 1.0.2 + AP 4.4.4 = Success
3) SP Racing BL + SSBL 1.0.2 + AP 4.5.0 (beta)= Fail
4) AP BL + SSBL 1.0.2 + AP 4.4.4 = Fail
5) AP BL + SSBL 1.0.2 + AP 4.5.0 (beta) = Success (edited)

I also did a PR for the SSBL and posted a binary for 1.0.2, here: https://github.com/spracing/ssbl/pull/5

more details in the commit message.

There's also an issue with the wrong start address in the `ardupilot.hex` files of every `.hex` released so far (as of 2024/03/14) , so do not even try and use them until they are corrected.  Using Mission Planner with the AP bootloader to flash the `ardupilot.adj` file works as expected.

I have fed this back to the AP devs working on the SPRacing H7 boards.

**Comment by hydra** [comment]
closing as completed.
